### ISSUE TITLE
After creating a project, I get a Dependencies Error

### ISSUE THREAD

**Issue by roddharris** [aurelia/dotnet#1]
I created a project using the following:

    dotnet new -i aurelia.dotnet.templates
    dotnet new aurelia -b webpack -t typescript -e none -ht http2 -c sass -p typical

I opened the project in VS 2017 and I see the little yellow triangle on the Dependencies area.  If I open that up, I see the following error under `Dependencies\NuGet\Aurelia.DotNet (1.0.0)`

     Project dependency Aurelia.DotNet does not contain an inclusive lower bound.  Include a lower bound in the dependency version to ensure consistent restore results.

Based on the message, I'm guessing that is something that needs to be done in the `aurelia/dotnet` project as opposed to something I need to do in my code correct?

**Comment by brandonseydel** [comment]
Just ignore that error for now.  We are jumping versions quite a bit on that one so I haven't versioned it yet.  Besides this how are things working for you?

**Comment by roddharris** [comment]
Like what I see so far -- very quick and easy!  It is appearing as though this is a very young project at this point -- still going through a lot of changes.  When do you think you'll have a "stable" version ready for generating a production ready starting point?

**Comment by roddharris** [comment]
Another question.  I'm not super familiar with Docker but I noticed a Dockerfile in the project.  Can the project be used without Docker or is Docker a requirement in the way that things are being set up?

**Comment by brandonseydel** [comment]
Docker will be integrated into the flow as well.  I was going to add a --docker option to the project.

**Comment by brandonseydel** [comment]
There is also a VSIX that integrates with this template to generate from a GUI.  This will also spin off into a stand alone Aurelia CLI scaffolding application where all these options will be represented in a universal GUI

**Comment by roddharris** [comment]
Nice, that was actually my next question! :)

**Comment by brandonseydel** [comment]
Here is a preview of the official VSIX which is pretty close to launch.
https://media.discordapp.net/attachments/555392517751963659/556666162507677716/unknown.png
Also if you have ever used add empty file from mads then  we have something similar 

Add aurelia file... which will very quickly take a file name and convention based generation of files with a global option to auto add to the resources global

**Comment by arjendeblok** [comment]
Wow, looks very good and promising. Cannot wait to use it in my project.

**Comment by roddharris** [comment]
BTW, a couple of the things I love about the way you organize the project.

1. You have everything contained in a ClientApp folder so that I'm not having to wade through all the client app config files at the project level. -- Nice!
2. You're serving up the SPA portion of the app without having to have an MVC Controller and View to do so.

**Comment by brandonseydel** [comment]
Fixed with version 1.3 which also enabled some other features
