### ISSUE TITLE
basic install setup

### ISSUE THREAD

**Issue by airboss001** [aurelia/dotnet#3]
Wanted to put a few notes here on my experience trying to get this to run.

Here are the manual steps followed:
dotnet new -i aurelia.dotnet.templates
dotnet new aurelia -ht http2 -c sass -e none

Additional Steps:
cd ClientApp
npm i
au build

cd ../project.Spa
dotnet run
[failing messages, can't find ClientApp]

Troubleshooting steps:
Trying to do the command 'dotnet run' in the project.Spa directory now fails. It is looking for 'ClientApp' to be in the same directory, not on level up. 

Moving ClientApp from the solution root into the 'project.Spa' directory now allows it to start and opening a browser to 'localhost:8080' loads the site.

I tried using the --secure and failed miserably, but that was before I discovered the above required steps. So I'll go back and try that.

**Comment by airboss001** [comment]
Going back to using the flag --secure the command:
dotnet run /seed
is failing with 
```
Couldn't find a project to run. Ensure a project exists in G:\2019\ASP.Net Core\Apptest4-secure, or pass the path to the project using --project.
```

**Comment by brandonseydel** [comment]
**There is a bug on first execute if the aurelia-cli package is not yet installed.** 
After that run 
```dotnet new aurelia --secure```
then deny the auto seed
**Just found a bug in the Spa project Helpers\DesignTimeContextFactory.cs REMOVE SecureSpa and only do Spa**
Then just run the project and that is it!  I will clean up the bugs and push a release tonight.

**Comment by airboss001** [comment]
Thanks @brandonseydel  for the update.

I'm interested in looking at that, and just wanted to do the id10t test for you.
It appears I am excelling at that task ;)

**Comment by brandonseydel** [comment]
Did everything work for you after those recommendations?

**Comment by airboss001** [comment]
I'll try it in the morning, and post here when I do.

**Comment by brandonseydel** [comment]
I will have a new version for you by then ;)

**Comment by brandonseydel** [comment]
1.3.0 released.  Everything should be good other than docker has one small hiccup.

**Comment by arjendeblok** [comment]
Where did you release this version 1.3.0?

**Comment by brandonseydel** [comment]
it goes to nuget.org technically you can update by rerunning the install command
dotnet new -i aurelia.dotnet.templates

**Comment by airboss001** [comment]
Ok, so I installed the new version with:
dotnet new -i aurelia.dotnet.templates

and then in a new project directory:
dotnet new aurelia --secure

Opening the project in VS2017
All the project references are bad for:
Model
Logic
DataAccess

Removed the bad references and added back the project references.

Running build causes a fail with the following message:
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6003	The specified task executable "cmd.exe" could not be run. The working directory "ClientApp\" does not exist.	Apptest4-secure.Spa	G:\2019\ASP.Net Core\Apptest4-secure\Apptest4-secure.Spa\Apptest4-secure.Spa.csproj	71	

Moved ClientApp from solution root into Spa root
Error goes away, and now it installs the npm modules, and 4 successful project builds.

Starting Debug Apptest4-secure.Spa and errors out on SeedAsync()
```
        public void Seed()
        {
            this.SeedAsync().Wait();
        }
```

System.AggregateException: 'One or more errors occurred. (Could not load file or assembly 'Apptest4_secure.Spa, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.)'

FileNotFoundException: Could not load file or assembly 'Apptest4_secure.Spa, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

**Comment by brandonseydel** [comment]
Lots of problems stemmed from a - in the folder name it appears.

**Comment by airboss001** [comment]
hmm...never even crossed my mind. Let me remove that, and put that in my notes of DOH!

**Comment by brandonseydel** [comment]
Would you be willing to guinea pig some of the new VSIX stuff?

**Comment by airboss001** [comment]
Ok, so removing the dash from the path fixed it. Man, am I good, or am I just really really unlucky! lol

Hey, whatever I can do to help, would be glad to. Apparently I am good at breaking stuff that works for everyone else :p

**Comment by brandonseydel** [comment]
I’ll publish a pre release vsix in the coming days and we can start.
